# 测试矩阵，cloud_placements * data_size * read
network_test:
  matrix:
    cloud_placements:
      - [1,1,1,1]
    data_sizes:
      - 10240
      - 10485760
    reads:
      - true
      - false
  start_datetime: 2022-11-01 13:30:00
  end_datetime: 2022-11-02 13:30:00
  interval: 30
  N: 4
  k: 3
  n: 2
  intermediate_save_seconds: 3600

# 测试可视化
network_test_visualization:
  # 分组粒度，单位秒
  group_size: 300
  # 计算的百分位数值
  percentage_values: [50, 99]